aliases:
# Cache Management
  - &restore-cache-gradle
    keys:
      - v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      # Fallback in case checksum fails
      - v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-
      - v1-gradle-{{ arch }}-{{ .Branch }}-
      # Fallback in case this is a first-time run on a fork
      - v1-gradle-{{ arch }}-master-
  - &save-cache-gradle
    paths:
      - ~/.gradle
    key: v1-gradle-{{ arch }}-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}

version: 2
jobs:
  build:
    working_directory: ~/fresco
    docker:
      - image: circleci/android@sha256:698557baed28b90b19f9988fb214e94376e5c04b44eec96423975d464b59a53e
    steps:
      - checkout
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Setup NDK
          command: |
            wget --quiet https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
            unzip -q android-ndk-r17b-linux-x86_64.zip -d /home/circleci
            echo "ndk.dir=/home/circleci/android-ndk-r17b" >> /home/circleci/fresco/local.properties
      - run:
          name: "NDK Fix: https://github.com/android-ndk/ndk/issues/188"
          command: sudo apt-get install file
      - run:
          name: Setup emulator
          command: |
            sdkmanager "system-images;android-19;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-19;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: |
            cd ${ANDROID_HOME}/emulator;ls
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            ldd emulator
            ldd `which pulseaudio`
            emulator -avd test -no-audio -no-window            
          background: true
