'\" t
.\"     Title: gif2rgb
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2 May 2012
.\"    Manual: GIFLIB Documentation
.\"    Source: GIFLIB
.\"  Language: English
.\"
.TH "GIF2RGB" "1" "2 May 2012" "GIFLIB" "GIFLIB Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gif2rgb \- convert images saved as GIF to 24\-bit RGB triplets
.SH "SYNOPSIS"
.HP \w'\fBgif2rgb\fR\ 'u
\fBgif2rgb\fR [\-v] [\-1] [\-c\ \fIcolors\fR] [\-s\ \fIwidth\fR\ \fIheight\fR] [\-o\ \fIoutfile\fR] [\-h] [\fIgif\-file\fR]
.SH "OPTIONS"
.PP
\-v
.RS 4
Verbose mode (show progress)\&. Enables printout of running scan lines\&.
.RE
.PP
\-1
.RS 4
Only one file in the format of RGBRGB\&.\&.\&. triplets (Each of R, G,B is a byte) is being read or written\&. This file size is 3 * Width * Height\&. If stdin is used for input or stdout for output, this option is implicitly applied\&. The default (if not `\-1\*(Aq) is 3 files with the names OutFileName\&.R, OutFileName\&.G, OutFileName\&.B, each of which is Width * Height bytes\&.
.RE
.PP
\-c colors
.RS 4
Specifies number of colors to use in RGB\-to\-GIF conversions, in bits per pixels, so \*(Aq\-c 8\*(Aq actually specifies 256 colors (maximum and default)\&.
.RE
.PP
\-s width height
.RS 4
Sets RGB\-to\-GIF conversion mode and specifies the size of the image to read\&.
.RE
.PP
\-o
.RS 4
specifies the name of the out file (see also `\-1\*(Aq above)\&.
.RE
.PP
\-h
.RS 4
Print one line of command line help, similar to Usage above\&.
.RE
.PP
By default, convert a GIF input file to RGB triplets\&. If \-s is specified, convert RGB input to a GIF\&.
.PP
If no input file is given, gif2rgb will try to read adata from stdin\&.
.SH "AUTHOR"
.PP
Gershon Elber\&.
