'\" t
.\"     Title: gifecho
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2 May 2012
.\"    Manual: GIFLIB Documentation
.\"    Source: GIFLIB
.\"  Language: English
.\"
.TH "GIFECHO" "1" "2 May 2012" "GIFLIB" "GIFLIB Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gifecho \- generate a GIF from ASCII text
.SH "SYNOPSIS"
.HP \w'\fBgifecho\fR\ 'u
\fBgifecho\fR [\-v] [\-s\ \fIcolormap\-size\fR] [\-f\ \fIforeground\fR] [\-c\ \fIR\fR\ \fIG\fR\ \fIB\fR] [\-t\ \fItext\fR] [\-h] [\fIgif\-file\fR]
.SH "DESCRIPTION"
.PP
A program to generate GIF images out of regular text\&. Text can be one line or multi\-line, and is converted using 8 by 8 fixed font\&.
.PP
This program reads stdin if no text is provided on the command line (\-t), and will dump the created GIF file to stdout\&.
.SH "OPTIONS"
.PP
\-v
.RS 4
Verbose mode (show progress)\&. Enables printout of running scan lines\&.
.RE
.PP
\-s colormap\-size
.RS 4
Explicitly defines the size of the color map of the resulting gif image\&. Usually the image will be bicolor with fg as color 1, unless [\-f] is explicitly given in case the color map size will be big enough to hold it\&. However it is sometimes convenient to set the color map size to certain size while the fg color is small mainly so this image may be merged with another (images must match color map size)\&.
.RE
.PP
\-f foreground
.RS 4
Select foreground index (background is always 0)\&. By default it is one and therefore the image result is bicolored\&. if FG is set to n then color map will be created with 2^k entries where 2^k > n for minimum k, assuming k <= 8\&. This color map will be all zeros except this forground index\&. This option is useful if this text image should be integrated into other image colormap using their colors\&.
.RE
.PP
\-c R G B
.RS 4
The color to use as the foreground color\&. White by default\&.
.RE
.PP
\-t text
.RS 4
One line of text can be provided on the command line\&. Note you must encapsulate the Text within quotes if it has spaces (The quotes themselves are not treated as part of the text)\&. If no \-t option is provided, stdin is read until end of file\&.
.RE
.PP
\-h
.RS 4
Print one line command line help, similar to Usage above\&.
.RE
.SH "NOTES"
.PP
There is a hardcoded limit of 100 the number of lines\&.
.SH "AUTHOR"
.PP
Gershon Elber\&.
