'\" t
.\"     Title: gifinto
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2 May 2012
.\"    Manual: GIFLIB Documentation
.\"    Source: GIFLIB
.\"  Language: English
.\"
.TH "GIFINTO" "1" "2 May 2012" "GIFLIB" "GIFLIB Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gifinto \- save GIF on stdin to file if size over set threshold
.SH "SYNOPSIS"
.HP \w'\fBgifinto\fR\ 'u
\fBgifinto\fR [\-v] [\-s\ \fIminsize\fR] [\-h] [\fIoutfile\fR]
.SH "DESCRIPTION"
.PP
A program to save stdin into a file with given name, iff the result file has size bigger than specified (see below)\&. This can be used to save a result under the same filename we started with in a chain of pipes\&.
.PP
Always reads a GIF file from stdin\&.
.SH "OPTIONS"
.PP
\-v
.RS 4
Verbose mode (show progress)\&. Enables printout of running scan lines\&.
.RE
.PP
\-s MinFileSize
.RS 4
If file is less than MinFileSize, it is deleted and not renamed to the given name\&. This will prevent killing the file we started with if the result is an empty file, or the pipeline did not complete\&.
.sp
The default file threshold size is 14 bytes, which is 1 bigger than GIF file stamp (6 bytes) plus a GIF file screen descriptor (7 bytes), so a GIF file with only GIF stamp and screen descriptor will not be renamed\&.
.RE
.PP
\-h
.RS 4
Print one line of command line help, similar to Usage above\&.
.RE
.SH "AUTHOR"
.PP
Gershon Elber\&.
