'\" t
.\"     Title: giflib
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 3 June 2012
.\"    Manual: GIFLIB Documentation
.\"    Source: GIFLIB
.\"  Language: English
.\"
.TH "GIFLIB" "1" "3 June 2012" "GIFLIB" "GIFLIB Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
giflib \- GIFLIB utilities
.SH "DESCRIPTION"
.PP
GIFLIB is a linkable service library and a set of utilities for processing images encoded using GIF (Graphics Interchange Format)\&.
.PP
These utilities are not intended to compete with or replace multi\-format graphics toolkits like ImageMagick or the Python Imaging Library, or graphics editors such as the GIMP\&. Find one of those, or an equivalent, if you need to crop, scale, rotate, toggle interlacing, or perform other conventional image transformations\&. Rather, these are intended to facilitate GIF\-specific operations which multi\-format tools may not adequately support\&.
.PP
API documentation for the service library is best viewed through a browser at the project website: http://sourceforge\&.net/projects/giflib/?source=directory\&.
.SH "SEE ALSO"
.PP
\fBgif2raw\fR(1),
\fBgif2rgb\fR(1),
\fBgifbuild\fR(1),
\fBgifecho\fR(1),
\fBgiffix\fR(1),
\fBgifinter\fR(1),
\fBgifinto\fR(1),
\fBgiftext\fR(1),
\fBgiftool\fR(1),
\fBgifclrmap\fR(1)\&.
.SH "AUTHORS"
.PP
Gershon Elber, Eric S\&. Raymond, Toshio Kuratomi\&.
