'\" t
.\"     Title: giftool
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 3 June 2012
.\"    Manual: GIFLIB Documentation
.\"    Source: GIFLIB
.\"  Language: English
.\"
.TH "GIFTOOL" "1" "3 June 2012" "GIFLIB" "GIFLIB Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
giftool \- GIF transformation tool
.SH "SYNOPSIS"
.HP \w'\fBgiftool\fR\ 'u
\fBgiftool\fR [\-a\ \fIaspect\fR] [\-b\ \fIbgcolor\fR] [\-d\ \fIdelaytime\fR] [\-i\ \fIinterlacing\fR] [\-n\ \fIimagelist\fR] [\-p\ \fIleft,top\fR] [\-s\ \fIwidth,height\fR] [\-t\ \fItranscolor\fR] [\-u\ \fIsort\-flag\fR] [\-x\ \fIdisposal\fR] [\-z\ \fIsort\-flag\fR]
.SH "DESCRIPTION"
.PP
A filter for transforming GIFS\&. With no options, it\*(Aqs an expensive copy of a GIF in standard input to standard output\&. Options specify filtering operations and are performed in the order specified on the command line\&.
.PP
The \-n option selects images, allowing the tool to act on a subset of images in a multi\-image GIF\&. This option takes a comma\-separated list of decimal integers which are interpreted as 1\-origin image indices; these are the images that will be acted on\&. If no \-n option is specified, the tool will select and transform all images\&.
.PP
The \-b option takes a decimal integer argument and uses it to set the (0\-origin) screen background color index\&.
.PP
The \-f option accepts a printf\-style format string and substitutes into it the values of image\-descriptor and graphics\-control fields\&. The string is formatted and output once for each selected image\&. Normal C\-style escapes \eb, \ef, \en, \er, \et\&. \ev, and \exNN are interpreted; also \ee produces ESC (ASCII 0x1b)\&. The following format cookies are substituted:
.PP
%a
.RS 4
Pixel aspect byte\&.
.RE
.PP
%b
.RS 4
Screen background color\&.
.RE
.PP
%d
.RS 4
Image delay time
.RE
.PP
%h
.RS 4
Image height (y dimension)
.RE
.PP
%n
.RS 4
Image index
.RE
.PP
%p
.RS 4
Image position (as an x,y pair)
.RE
.PP
%s
.RS 4
Screen size (as an x,y pair)
.RE
.PP
%t
.RS 4
Image transparent\-color index
.RE
.PP
%u
.RS 4
Image user\-input flag (boolean)
.RE
.PP
%v
.RS 4
GIF version string
.RE
.PP
%w
.RS 4
Image width (x dimension)
.RE
.PP
%x
.RS 4
Image GIF89 disposal mode
.RE
.PP
%z
.RS 4
Image\*(Aqs color table sort flag (boolean, false if no local color map)
.RE
.PP
Boolean substitutions may take a prefix to modify how they are displayed:
.PP
1
.RS 4
"1" or "0"
.RE
.PP
o
.RS 4
"on" or "off"
.RE
.PP
t
.RS 4
"t" or "f"
.RE
.PP
y
.RS 4
"yes" or "no"
.RE
.PP
Thus, for example, "%oz" displays image sort flags using the strings "on" and "off"\&. The default with no prefix is numeric\&.
.PP
The \-a option takes an unsigned decimal integer argument and uses it to set the aspect\-ratio bye in the logical screen descriptor block\&.
.PP
The \-b option takes an unsigned decimal integer argument and uses it to set the background color index in the logical screen descriptor block\&.
.PP
The \-d option takes a decimal integer argument and uses it to set a delay time, in hundredths of a second, on selected images\&.
.PP
The \-i option sets or clears interlaccing in selected images\&. Acceptable arguments are "1", "0", "yes", "no", "on", "off", "t", "f"
.PP
The \-p option takes a (0\-origin) x,y coordinate\-pair and sets it as the preferred upper\-left\-corner coordinates of selected images\&.
.PP
The \-s option takes a (0\-origin) x,y coordinate\-pair and sets it as the expected display screen size\&.
.PP
The \-t option takes a decimal integer argument and uses it to set the (0\-origin) index of the transparency color in selected images\&.
.PP
The \-u option sets or clears the user\-input flag in selected images\&. Acceptable arguments are "1", "0", "yes", "no", "on", "off", "t", "f"\&.
.PP
The \-x option takes a decimal integer argument and uses it to set the GIF89 disposal mode in selected images\&.
.PP
The \-z option sets or clears the color\-table sort flag in selected images\&. Acceptable arguments are "1", "0", "yes", "no", "on", "off", "t", "f"\&.
.PP
Note that the \-a, \-b, \-p, \-s, and \-z options are included to complete the ability to modify all fields defined in the GIF standard, but should have no effect on how an image renders on browsers or modern viewers\&.
.SH "AUTHOR"
.PP
Eric S\&. Raymond\&.
