/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

package com.facebook.storage

import com.facebook.storage.config.size.SizeConfig
import com.facebook.storage.config.stale.StaleConfig
import com.facebook.storage.config.userscope.UserScopeConfig

/**
 * Stub PathsRegistry for the IG Image Loader sample app.
 *
 * In production, this class is auto-generated by [SuperStoreCodeGenerator] from storage config
 * files in `//xplat/storageconfigs/`. The sample app binary doesn't include the Ultralight codegen
 * pipeline, so we provide this stub with safe defaults.
 *
 * All methods return values that allow the storage chain ([IGAppsStorageDependencySupplier] →
 * [IgCask] → [IgStashFactory]) to initialize without crashing.
 */
object PathsRegistry {

  @JvmStatic fun getAllIds(): IntArray = intArrayOf()

  @JvmStatic fun getLabelForId(id: Int): String = "sample_storage_$id"

  @JvmStatic fun getConfigNameForId(id: Int): String = "sample_config_$id"

  @JvmStatic fun getBasePathTypeForId(id: Int): Int = 3 // BASE_PATH_TYPE_CACHE

  @JvmStatic fun getBasePathForId(id: Int): String = "cache/sample_storage_$id"

  @JvmStatic fun getExtrasForId(id: Int): String? = null

  @JvmStatic fun getUserScopeForId(id: Int): UserScopeConfig = UserScopeConfig.NOT_SCOPED

  @JvmStatic fun getSizeConfigForId(id: Int): SizeConfig? = null

  @JvmStatic fun getStaleConfigForId(id: Int): StaleConfig? = null

  @JvmStatic fun getVersionForId(id: Int): Long = 0

  @JvmStatic fun getPivotName(id: Int): String? = null
}
